-- DEV ONLY: wipe data but keep migration history
TRUNCATE TABLE
  "CreditNoteItem",
  "CreditNote",
  "SaleInstallment",
  "SaleItemLot",
  "SaleItem",
  "SalePayment",
  "Sale",
  "PurchaseInstallment",
  "PurchasePayment",
  "PurchaseItem",
  "Purchase",
  "StockMovement",
  "StockLot",
  "ProductPresentation",
  "ProductComponent",
  "Product",
  "Tax",
  "Category",
  "MeasurementUnit",
  "Depot",
  "Client",
  "Supplier",
  "CashCount",
  "CashRegister",
  "PaymentMethod",
  "ExchangeRate",
  "Subscription",
  "BusinessMember",
  "Role",
  "UserContact",
  "User",
  "Business",
  "BusinessCategory"
RESTART IDENTITY CASCADE;
