import type { PermissionModule, PrismaClient } from "@prisma/client";

export const permissions: { code: string; name: string; module: PermissionModule }[] = [
  { code: "BUSINESS_SETTINGS_VIEW", name: "Ver configuracion del negocio", module: "BUSINESS" },
  { code: "BUSINESS_SETTINGS_EDIT", name: "Editar configuracion del negocio", module: "BUSINESS" },
  { code: "BUSINESS_POLICIES_EDIT", name: "Editar politicas del negocio", module: "BUSINESS" },
  { code: "BUSINESS_EXCHANGE_RATE_EDIT", name: "Editar tasa de cambio del negocio", module: "BUSINESS" },
  { code: "MEMBERS_VIEW", name: "Ver miembros", module: "MEMBERS" },
  { code: "MEMBERS_MANAGE", name: "Gestionar miembros", module: "MEMBERS" },
  { code: "CLIENTS_READ", name: "Ver clientes", module: "CLIENTS" },
  { code: "CLIENTS_WRITE", name: "Gestionar clientes", module: "CLIENTS" },
  { code: "SUPPLIERS_READ", name: "Ver proveedores", module: "SUPPLIERS" },
  { code: "SUPPLIERS_WRITE", name: "Gestionar proveedores", module: "SUPPLIERS" },
  { code: "PRODUCTS_READ", name: "Ver productos", module: "PRODUCTS" },
  { code: "PRODUCTS_WRITE", name: "Gestionar productos", module: "PRODUCTS" },
  { code: "CATEGORIES_READ", name: "Ver categorias", module: "CATEGORIES" },
  { code: "CATEGORIES_WRITE", name: "Gestionar categorias", module: "CATEGORIES" },
  { code: "PRESENTATIONS_READ", name: "Ver presentaciones", module: "PRESENTATIONS" },
  { code: "PRESENTATIONS_WRITE", name: "Gestionar presentaciones", module: "PRESENTATIONS" },
  { code: "DEPOSITS_READ", name: "Ver depositos", module: "DEPOSITS" },
  { code: "DEPOSITS_WRITE", name: "Gestionar depositos", module: "DEPOSITS" },
  { code: "STOCK_MOVEMENTS_READ", name: "Ver movimientos de stock", module: "STOCK" },
  { code: "STOCK_MOVEMENTS_WRITE", name: "Gestionar movimientos de stock", module: "STOCK" },
  { code: "CASH_REGISTER_READ", name: "Ver caja", module: "CASH_REGISTER" },
  { code: "CASH_REGISTER_OPEN", name: "Abrir caja", module: "CASH_REGISTER" },
  { code: "CASH_REGISTER_CLOSE", name: "Cerrar caja", module: "CASH_REGISTER" },
  { code: "CASH_COUNT", name: "Arqueo de caja", module: "CASH_REGISTER" },
  { code: "CREDITS_SALES_COLLECT", name: "Cobrar creditos de venta", module: "CREDITS" },
  { code: "CREDITS_PURCHASES_PAY", name: "Pagar creditos de compra", module: "CREDITS" },
  { code: "CREDIT_NOTES_CREATE", name: "Crear notas de credito", module: "CREDITS" },
  { code: "INVENTORY_READ", name: "Ver inventario", module: "INVENTORY" },
  { code: "INVENTORY_WRITE", name: "Gestionar inventario", module: "INVENTORY" },
  { code: "SALES_READ", name: "Ver ventas", module: "SALES" },
  { code: "SALES_WRITE", name: "Gestionar ventas", module: "SALES" },
  { code: "PROCUREMENT_READ", name: "Ver compras", module: "PROCUREMENT" },
  { code: "PROCUREMENT_WRITE", name: "Gestionar compras", module: "PROCUREMENT" },
  { code: "FINANCE_READ", name: "Ver finanzas", module: "FINANCE" },
  { code: "REPORTS_DASHBOARD_VIEW", name: "Ver dashboard de reportes", module: "REPORTS" },
  { code: "REPORTS_SALES_VIEW", name: "Ver reporte de ventas", module: "REPORTS" },
  { code: "REPORTS_PURCHASES_VIEW", name: "Ver reporte de compras", module: "REPORTS" },
  { code: "REPORTS_INVENTORY_VIEW", name: "Ver reporte de inventario", module: "REPORTS" },
  { code: "REPORTS_CASH_REGISTER_VIEW", name: "Ver reporte de caja", module: "REPORTS" },
  { code: "REPORTS_COLLECTIONS_VIEW", name: "Ver reporte de cobros", module: "REPORTS" },
  { code: "REPORTS_FINANCIAL_VIEW", name: "Ver reporte financiero", module: "REPORTS" },
  { code: "REPORTS_DEPOSITS_VIEW", name: "Ver reporte de depósitos", module: "REPORTS" },
  { code: "REPORTS_CREDITS_VIEW", name: "Ver reporte de créditos", module: "REPORTS" },
  { code: "TABLES_READ", name: "Ver mesas", module: "RESTAURANT" },
  { code: "TABLES_WRITE", name: "Gestionar mesas", module: "RESTAURANT" },
  { code: "ORDERS_READ", name: "Ver pedidos", module: "RESTAURANT" },
  { code: "ORDERS_WRITE", name: "Gestionar pedidos", module: "RESTAURANT" },
];

export const rolePermissions: Record<string, string[]> = {
  OWNER: permissions.map((permission) => permission.code),
  ADMIN: [
    "BUSINESS_SETTINGS_VIEW",
    "BUSINESS_SETTINGS_EDIT",
    "BUSINESS_EXCHANGE_RATE_EDIT",
    "BUSINESS_POLICIES_EDIT",
    "MEMBERS_VIEW",
    "MEMBERS_MANAGE",
    "CLIENTS_READ",
    "CLIENTS_WRITE",
    "SUPPLIERS_READ",
    "SUPPLIERS_WRITE",
    "PRODUCTS_READ",
    "PRODUCTS_WRITE",
    "CATEGORIES_READ",
    "CATEGORIES_WRITE",
    "PRESENTATIONS_READ",
    "PRESENTATIONS_WRITE",
    "DEPOSITS_READ",
    "DEPOSITS_WRITE",
    "STOCK_MOVEMENTS_READ",
    "STOCK_MOVEMENTS_WRITE",
    "CASH_REGISTER_READ",
    "CASH_REGISTER_OPEN",
    "CASH_REGISTER_CLOSE",
    "CASH_COUNT",
    "CREDITS_SALES_COLLECT",
    "CREDITS_PURCHASES_PAY",
    "CREDIT_NOTES_CREATE",
    "INVENTORY_READ",
    "INVENTORY_WRITE",
    "SALES_READ",
    "SALES_WRITE",
    "PROCUREMENT_READ",
    "PROCUREMENT_WRITE",
    "FINANCE_READ",
    "REPORTS_DASHBOARD_VIEW",
    "REPORTS_SALES_VIEW",
    "REPORTS_PURCHASES_VIEW",
    "REPORTS_INVENTORY_VIEW",
    "REPORTS_CASH_REGISTER_VIEW",
    "REPORTS_COLLECTIONS_VIEW",
    "REPORTS_FINANCIAL_VIEW",
    "REPORTS_DEPOSITS_VIEW",
    "REPORTS_CREDITS_VIEW",
    "TABLES_READ",
    "TABLES_WRITE",
    "ORDERS_READ",
    "ORDERS_WRITE",
  ],
  OPERATOR: [
    "CLIENTS_READ",
    "CLIENTS_WRITE",
    "PRODUCTS_READ",
    "DEPOSITS_READ",
    "SALES_READ",
    "SALES_WRITE",
    "CREDITS_SALES_COLLECT",
    "CREDIT_NOTES_CREATE",
    "CASH_REGISTER_READ",
    "CASH_REGISTER_OPEN",
    "CASH_REGISTER_CLOSE",
    "CASH_COUNT",
    "REPORTS_DASHBOARD_VIEW",
    "REPORTS_SALES_VIEW",
    "REPORTS_PURCHASES_VIEW",
    "REPORTS_CASH_REGISTER_VIEW",
    "FINANCE_READ",
    "TABLES_READ",
    "TABLES_WRITE",
    "ORDERS_READ",
    "ORDERS_WRITE",
  ],
  AUDITOR: [
    "BUSINESS_SETTINGS_VIEW",
    "MEMBERS_VIEW",
    "CLIENTS_READ",
    "SUPPLIERS_READ",
    "PRODUCTS_READ",
    "CATEGORIES_READ",
    "PRESENTATIONS_READ",
    "DEPOSITS_READ",
    "STOCK_MOVEMENTS_READ",
    "CASH_REGISTER_READ",
    "INVENTORY_READ",
    "SALES_READ",
    "PROCUREMENT_READ",
    "FINANCE_READ",
    "REPORTS_DASHBOARD_VIEW",
    "REPORTS_SALES_VIEW",
    "REPORTS_PURCHASES_VIEW",
    "REPORTS_INVENTORY_VIEW",
    "REPORTS_CASH_REGISTER_VIEW",
    "REPORTS_COLLECTIONS_VIEW",
    "REPORTS_FINANCIAL_VIEW",
    "REPORTS_DEPOSITS_VIEW",
    "REPORTS_CREDITS_VIEW",
    "TABLES_READ",
    "ORDERS_READ",
  ],
  MANAGER: [
    "BUSINESS_SETTINGS_VIEW",
    "BUSINESS_SETTINGS_EDIT",
    "BUSINESS_EXCHANGE_RATE_EDIT",
    "BUSINESS_POLICIES_EDIT",
    "MEMBERS_VIEW",
    "MEMBERS_MANAGE",
    "CLIENTS_READ",
    "CLIENTS_WRITE",
    "SUPPLIERS_READ",
    "SUPPLIERS_WRITE",
    "PRODUCTS_READ",
    "PRODUCTS_WRITE",
    "CATEGORIES_READ",
    "CATEGORIES_WRITE",
    "PRESENTATIONS_READ",
    "PRESENTATIONS_WRITE",
    "DEPOSITS_READ",
    "DEPOSITS_WRITE",
    "STOCK_MOVEMENTS_READ",
    "STOCK_MOVEMENTS_WRITE",
    "CASH_REGISTER_READ",
    "CASH_REGISTER_OPEN",
    "CASH_REGISTER_CLOSE",
    "CASH_COUNT",
    "CREDITS_SALES_COLLECT",
    "CREDITS_PURCHASES_PAY",
    "CREDIT_NOTES_CREATE",
    "INVENTORY_READ",
    "INVENTORY_WRITE",
    "SALES_READ",
    "SALES_WRITE",
    "PROCUREMENT_READ",
    "PROCUREMENT_WRITE",
    "FINANCE_READ",
    "REPORTS_DASHBOARD_VIEW",
    "REPORTS_SALES_VIEW",
    "REPORTS_PURCHASES_VIEW",
    "REPORTS_INVENTORY_VIEW",
    "REPORTS_CASH_REGISTER_VIEW",
    "REPORTS_COLLECTIONS_VIEW",
    "REPORTS_FINANCIAL_VIEW",
    "REPORTS_DEPOSITS_VIEW",
    "REPORTS_CREDITS_VIEW",
    "TABLES_READ",
    "TABLES_WRITE",
    "ORDERS_READ",
    "ORDERS_WRITE",
  ],
  CASHIER: [
    "BUSINESS_SETTINGS_VIEW",
    "CATEGORIES_READ",
    "CLIENTS_READ",
    "CLIENTS_WRITE",
    "PRODUCTS_READ",
    "DEPOSITS_READ",
    "SALES_READ",
    "SALES_WRITE",
    "CREDITS_SALES_COLLECT",
    "CREDIT_NOTES_CREATE",
    "CASH_REGISTER_READ",
    "CASH_REGISTER_OPEN",
    "CASH_REGISTER_CLOSE",
    "CASH_COUNT",
    "REPORTS_DASHBOARD_VIEW",
    "REPORTS_SALES_VIEW",
    "REPORTS_CASH_REGISTER_VIEW",
    "FINANCE_READ",
    "TABLES_READ",
    "TABLES_WRITE",
    "ORDERS_READ",
    "ORDERS_WRITE",
  ],
  SELLER: [
    "CLIENTS_READ",
    "CLIENTS_WRITE",
    "PRODUCTS_READ",
    "SALES_READ",
    "SALES_WRITE",
    "CREDITS_SALES_COLLECT",
    "REPORTS_SALES_VIEW",
    "TABLES_READ",
    "TABLES_WRITE",
    "ORDERS_READ",
    "ORDERS_WRITE",
  ],
  BUYER: [
    "SUPPLIERS_READ",
    "SUPPLIERS_WRITE",
    "PRODUCTS_READ",
    "DEPOSITS_READ",
    "DEPOSITS_WRITE",
    "STOCK_MOVEMENTS_READ",
    "STOCK_MOVEMENTS_WRITE",
    "CREDITS_PURCHASES_PAY",
    "PROCUREMENT_READ",
    "PROCUREMENT_WRITE",
    "INVENTORY_READ",
    "INVENTORY_WRITE",
    "REPORTS_PURCHASES_VIEW",
    "REPORTS_INVENTORY_VIEW",
    "REPORTS_DEPOSITS_VIEW",
  ],
  WAREHOUSE: [
    "PRODUCTS_READ",
    "CATEGORIES_READ",
    "PRESENTATIONS_READ",
    "DEPOSITS_READ",
    "DEPOSITS_WRITE",
    "STOCK_MOVEMENTS_READ",
    "STOCK_MOVEMENTS_WRITE",
    "INVENTORY_READ",
    "INVENTORY_WRITE",
    "REPORTS_INVENTORY_VIEW",
  ],
  ACCOUNTANT: [
    "BUSINESS_SETTINGS_VIEW",
    "CLIENTS_READ",
    "SUPPLIERS_READ",
    "CASH_REGISTER_READ",
    "CASH_COUNT",
    "CREDITS_SALES_COLLECT",
    "CREDITS_PURCHASES_PAY",
    "FINANCE_READ",
    "SALES_READ",
    "PROCUREMENT_READ",
    "REPORTS_DASHBOARD_VIEW",
    "REPORTS_SALES_VIEW",
    "REPORTS_PURCHASES_VIEW",
    "REPORTS_INVENTORY_VIEW",
    "REPORTS_CASH_REGISTER_VIEW",
    "REPORTS_COLLECTIONS_VIEW",
    "REPORTS_FINANCIAL_VIEW",
    "REPORTS_DEPOSITS_VIEW",
    "REPORTS_CREDITS_VIEW",
  ],
};

export const seedPermissions = async (prisma: PrismaClient) => {
  const currentCodes = new Set(permissions.map((p) => p.code));

  const existingPerms = await prisma.permission.findMany({ select: { id: true, code: true } });
  const toDelete = existingPerms.filter((p) => !currentCodes.has(p.code));

  if (toDelete.length > 0) {
    const ids = toDelete.map((p) => p.id);
    await prisma.rolePermission.deleteMany({ where: { permissionId: { in: ids } } });
    await prisma.permission.deleteMany({ where: { id: { in: ids } } });
    console.log(`🗑️  Removed ${ids.length} obsolete permissions: ${toDelete.map((p) => p.code).join(', ')}`);
  }

  await prisma.permission.createMany({
    data: permissions.map((permission) => ({
      code: permission.code,
      name: permission.name,
      module: permission.module,
    })),
    skipDuplicates: true,
  });

  const roles = await prisma.role.findMany({ select: { id: true, code: true } });
  const permissionsByCode = await prisma.permission.findMany({
    select: { id: true, code: true },
  });

  const permissionIdByCode = new Map(
    permissionsByCode.map((permission) => [permission.code, permission.id])
  );

  for (const role of roles) {
    const normalizedCode = role.code.trim().toUpperCase();
    const codes = rolePermissions[normalizedCode] || [];
    const data = codes
      .map((code) => {
        const permissionId = permissionIdByCode.get(code);
        if (!permissionId) return null;
        return { roleId: role.id, permissionId };
      })
      .filter(Boolean) as { roleId: number; permissionId: number }[];

    if (!data.length) continue;

    await prisma.rolePermission.deleteMany({ where: { roleId: role.id } });
    await prisma.rolePermission.createMany({
      data,
      skipDuplicates: true,
    });
  }
};
